### Context path
server:
  servlet:
    context-path: /api

spring:
  application:
    name: note-backend

  ### production
  config:
    activate:
      on-profile: production
  ### database configuration
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DATABASE:note}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.mariadb.jdbc.Driver
