### Context path
server:
  servlet:
    context-path: /api

### Api documentation
springdoc:
  swagger-ui:
    path: /docs

spring:
  #### database configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DATABASE:note}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.mariadb.jdbc.Driver